FROM node:24-bookworm-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
RUN npm prune --omit=dev && npm cache clean --force && rm -rf /usr/share/doc /usr/share/man /tmp/*

FROM node:24-slim
WORKDIR /app
COPY --from=builder /app /app
COPY . .
CMD ["node", "api.js"]
